services:
  vc-wallet-provider:
    build:
      context: .
    image: ds-vc-wallet:local
    ports:
      - "38082:8081"
    environment:
      VC_WALLET_PARTICIPANT_DID: did:web:provider.dataspaces.localhost
      VC_WALLET_CREDENTIALS_PATH: /credentials/provider
    volumes:
      - ../../credentials:/credentials:ro
    labels:
      traefik.enable: "false"

  vc-wallet-consumer:
    build:
      context: .
    image: ds-vc-wallet:local
    ports:
      - "38083:8081"
    environment:
      VC_WALLET_PARTICIPANT_DID: did:web:consumer.dataspaces.localhost
      VC_WALLET_CREDENTIALS_PATH: /credentials/consumer
    volumes:
      - ../../credentials:/credentials:ro
    labels:
      traefik.enable: "false"
