"""Shared EDC v5 Management API client and Pydantic models."""

from .client import (
    DEFAULT_API_VERSION,
    BearerAuth,
    EdcManagementClient,
    EdcPollTimeout,
    TokenSource,
)
from .odrl import OdrlConversionError, to_dsp_compact
from .schemas import (
    DATASPACE_PROTOCOL,
    DSP_PATH_SEGMENT,
    DSP_VERSION,
    MANAGEMENT_CONTEXT,
    TRANSFER_STARTED_EVENT,
    AssetCreate,
    CallbackAddress,
    CatalogRequest,
    ContractDefCreate,
    DataAddress,
    EdrResponse,
    FlowRequest,
    FlowResult,
    NegotiationRequest,
    NegotiationState,
    PolicyCreate,
    SyncResult,
    TransferRequest,
    TransferState,
)
from .webhooks import (
    ContractNegotiationEvent,
    TransferProcessEvent,
    TransferProcessStartedEvent,
)

__all__ = [
    "DEFAULT_API_VERSION",
    "MANAGEMENT_CONTEXT",
    "TRANSFER_STARTED_EVENT",
    "BearerAuth",
    "CallbackAddress",
    "OdrlConversionError",
    "TokenSource",
    "TransferProcessStartedEvent",
    "to_dsp_compact",
    "DATASPACE_PROTOCOL",
    "DSP_PATH_SEGMENT",
    "DSP_VERSION",
    "AssetCreate",
    "CatalogRequest",
    "ContractDefCreate",
    "ContractNegotiationEvent",
    "DataAddress",
    "EdcManagementClient",
    "EdcPollTimeout",
    "EdrResponse",
    "FlowRequest",
    "FlowResult",
    "NegotiationRequest",
    "NegotiationState",
    "PolicyCreate",
    "SyncResult",
    "TransferProcessEvent",
    "TransferRequest",
    "TransferState",
]
