{{- include "ds.externalSecret" (dict "ctx" . "remoteKey" (printf "federated-catalog-%s" .Values.participant.name) "keys" (list
    (dict "secretKey" "CATALOG_SERVICE_CLIENT_SECRET" "property" "service_client_secret"))) }}
