"""Governance v2 — ODRL-aware policy model for the dataspaces platform."""

from .models import (
    GovernanceOwner,
    GovernanceRule,
    GovernanceRuleV2,
    DataspacePolicy,
    DataspaceSpec,
    PolicyObligations,
    PolicyAudience,
    PolicyConsent,
    DataspaceAsset,
    DataspaceDataAddress,
    DataspaceContract,
    DpvMapping,
    OdrlProfile,
    PurposeConcept,
    SKOS_MATCH_RELATIONS,
    load_odrl_profile,
    subject_column,
)
from .dataplane import (
    ALLOW,
    DENY,
    DIRECT_USER_MATCH,
    DataplaneDecision,
    DataplaneRowFilter,
    DatasetVerdict,
    DecisionCache,
)
from .sharing import (
    CONSENT_BASIS,
    DPV_LEGAL_BASES,
    OfferCoverage,
    OfferRecipients,
    ProcessorCategory,
    SharingOffer,
    SharingOfferCatalogue,
    is_iso_duration,
    load_sharing_offers,
)
from .vocabularies import (
    JSONLD,
    Vocabulary,
    VocabularyError,
    VocabularyRegistry,
    load_vocabularies,
)
from .purposes import purpose_failure, unresolved_purposes
from .resolver import GovernanceConfig, GovernanceResolver
from .mapper import GovernanceMapper
from .matrix import build_policy_matrix, build_policy_matrix_entry
from .owners import (
    HttpOwnersRegistry,
    OwnerEntry,
    OwnersRegistry,
    load_owners_yaml,
)

__all__ = [
    "GovernanceOwner",
    "GovernanceRule",
    "GovernanceRuleV2",
    "DataspacePolicy",
    "DataspaceSpec",
    "PolicyObligations",
    "PolicyAudience",
    "PolicyConsent",
    "DataspaceAsset",
    "DataspaceDataAddress",
    "DataspaceContract",
    "DpvMapping",
    "OdrlProfile",
    "PurposeConcept",
    "SKOS_MATCH_RELATIONS",
    "load_odrl_profile",
    "subject_column",
    "ALLOW",
    "DENY",
    "DIRECT_USER_MATCH",
    "DataplaneDecision",
    "DataplaneRowFilter",
    "DatasetVerdict",
    "DecisionCache",
    "purpose_failure",
    "unresolved_purposes",
    "CONSENT_BASIS",
    "DPV_LEGAL_BASES",
    "OfferCoverage",
    "OfferRecipients",
    "ProcessorCategory",
    "SharingOffer",
    "SharingOfferCatalogue",
    "is_iso_duration",
    "load_sharing_offers",
    "JSONLD",
    "Vocabulary",
    "VocabularyError",
    "VocabularyRegistry",
    "load_vocabularies",
    "GovernanceConfig",
    "GovernanceResolver",
    "GovernanceMapper",
    "build_policy_matrix",
    "build_policy_matrix_entry",
    "OwnerEntry",
    "OwnersRegistry",
    "HttpOwnersRegistry",
    "load_owners_yaml",
]
