"""The DCP presentation exchange, across three processes that share nothing.

None of these could be made against a single instance: the holder verifies a
signature using a key it can only have obtained by resolving the verifier's DID
document over HTTP, and the credential it presents was signed by a **trust
anchor** whose private key lives in a third database it cannot read.

The anchor became a real third party in `T-2a`, when the harness moved onto the
enrolment handshake that replaced `ir-cli participant add` (`D-51`). Before that
the "anchor" was the same process as the holder, so the issuer check compared
two DIDs served by one instance.
"""

from __future__ import annotations

import base64
import json

import httpx
import pytest
from conftest import MEMBERSHIP_SCOPE, run_exchange

pytestmark = pytest.mark.integration


def _claims(jwt: str) -> dict:
    return json.loads(base64.urlsafe_b64decode(jwt.split(".")[1] + "===").decode())


def _query(scope: str = MEMBERSHIP_SCOPE) -> dict:
    return {
        "@context": ["https://w3id.org/dspace-dcp/v1.0/dcp.jsonld"],
        "@type": "PresentationQueryMessage",
        "scope": [scope],
    }


def _ask(holder, token: str, body: dict | None = None) -> httpx.Response:
    return httpx.post(
        f"{holder.url}/credentials/{holder.did}/presentations/query",
        json=body or _query(),
        headers={"Authorization": f"Bearer {token}"},
        timeout=15,
    )


# ── Publication and resolution are two halves of one thing ──────────────────


@pytest.mark.rule("P-6")
def test_each_registry_publishes_its_did_at_the_well_known_path(holder, verifier):
    for registry in (holder, verifier):
        response = httpx.get(f"{registry.url}/.well-known/did.json", timeout=10)
        assert response.status_code == 200
        assert response.json()["id"] == registry.did


@pytest.mark.rule("P-6")
def test_the_published_document_carries_a_usable_key(holder):
    document = httpx.get(f"{holder.url}/.well-known/did.json", timeout=10).json()
    method = document["verificationMethod"][0]
    assert method["publicKeyJwk"]["crv"] == "P-256"
    assert "d" not in method["publicKeyJwk"]


# ── The exchange ────────────────────────────────────────────────────────────


@pytest.mark.rule("P-8")
def test_a_verifier_with_a_grant_is_served(holder, verifier, dcp_exchange):
    """The call that used to 401 every time, now across two processes."""
    response = _ask(holder, dcp_exchange())
    assert response.status_code == 200, response.text
    assert response.json()["@type"] == "dcp:PresentationResponseMessage"


@pytest.mark.rule("P-3")
def test_the_presentation_carries_the_membership_credential(
    holder, verifier, dcp_exchange
):
    """Enrolment issued it; the exchange is what makes it reachable.

    The credential arrives because `ir-cli participant init --code` presented
    this instance's own key to the anchor and asked to be issued to — so a
    failure here is as likely to be a broken handshake as a broken exchange.
    """
    body = _ask(holder, dcp_exchange()).json()
    vp = _claims(body["dcp:presentation"]["@value"][0])
    assert vp["vp"]["holder"] == holder.did
    assert vp["aud"] == verifier.did
    credentials = vp["vp"]["verifiableCredential"]
    assert len(credentials) == 1
    assert "MembershipCredential" in _claims(credentials[0])["vc"]["type"]


@pytest.mark.rule("P-2")
def test_the_credential_is_signed_by_the_trust_anchor(holder, anchor, dcp_exchange):
    """Not merely *some other* DID — the anchor's, from a database the holder
    cannot read.

    `!= holder.did` was all this could claim while the anchor was the holder's
    own process under a different DID path. Naming the anchor is what makes it a
    statement about custody: the issuing key was generated by `ir-cli bootstrap`
    on a third instance, encrypted with that instance's own encryption key, and
    never sent anywhere.
    """
    body = _ask(holder, dcp_exchange()).json()
    vp = _claims(body["dcp:presentation"]["@value"][0])
    vc = _claims(vp["vp"]["verifiableCredential"][0])["vc"]
    assert vc["issuer"] == anchor.did
    assert vc["issuer"] != holder.did


def _status_list_urls(holder, dcp_exchange) -> dict[str, str]:
    """Every register the presented credential names, by purpose."""
    body = _ask(holder, dcp_exchange()).json()
    vp = _claims(body["dcp:presentation"]["@value"][0])
    vc = _claims(vp["vp"]["verifiableCredential"][0])["vc"]
    status = vc["credentialStatus"]
    entries = status if isinstance(status, list) else [status]
    return {e["statusPurpose"]: e["statusListCredential"] for e in entries}


def _status_list_url(holder, dcp_exchange) -> str:
    return _status_list_urls(holder, dcp_exchange)["revocation"]


@pytest.mark.rule("P-25")
def test_a_presented_credential_names_both_registers(holder, dcp_exchange):
    """Suspension is only a state if a verifier can read it.

    A participant credential that named the revocation register alone could be
    revoked and nothing else, so suspending its holder would set a bit nobody
    fetches — suspension as a slower revocation, which is the gap
    `participation.md` §5 records.
    """
    urls = _status_list_urls(holder, dcp_exchange)
    assert set(urls) == {"revocation", "suspension"}


@pytest.mark.rule("P-13")
def test_every_named_status_list_url_is_fetchable(holder, dcp_exchange):
    """A revocation check that cannot fetch the list fails closed.

    Every credential issued in dev carried an `https://` URL that dev does not
    serve, so this had never once been true. It is asserted here rather than in
    a unit test because only a running server can answer it — the URL is built
    from `public_base_url` and is the one value that outlives the process, since
    it is written *inside* every credential.

    It covers **both** registers now, and the suspension one is the more fragile
    of the two: nothing writes to it until somebody is first suspended, so a
    register created lazily on first use would 404 for every credential issued
    before then — and fail closed means those credentials are rejected.
    """
    for purpose, url in sorted(_status_list_urls(holder, dcp_exchange).items()):
        response = httpx.get(url, timeout=10)
        assert response.status_code == 200, f"{purpose}: {url} → {response.status_code}"


@pytest.mark.rule("P-8b")
def test_the_status_list_is_served_signed_by_default(holder, dcp_exchange):
    """The default body is a **VC-JWT**, not JSON-LD.

    An unsigned revocation list is one anyone on the path can rewrite: clear a
    bit and a revoked credential is accepted again. So the endpoint signs it and
    serves JSON only on an exact `Accept: application/json`, which is the way
    round EDC needs — it sends `Accept: */*` and parses the body as a JWT.

    This assertion is why the test above is no longer enough on its own: it read
    `response.json()` and so pinned the *unsigned* shape. It has not run since
    the signing landed, which is how it kept agreeing with a contract the service
    had stopped honouring.
    """
    url = _status_list_url(holder, dcp_exchange)
    body = httpx.get(url, timeout=10).text.strip()

    assert body.count(".") == 2 and not body.startswith("{"), (
        "the status list came back as something other than a compact JWS — an "
        "unsigned revocation list can be rewritten in transit"
    )
    assert "StatusList2021Credential" in _claims(body)["vc"]["type"]


def test_the_status_list_is_json_only_when_asked_for_exactly_that(holder, dcp_exchange):
    """The opt-in branch, pinned in the same place as the default."""
    url = _status_list_url(holder, dcp_exchange)
    response = httpx.get(url, headers={"Accept": "application/json"}, timeout=10)
    assert response.status_code == 200
    assert "StatusList2021Credential" in response.json()["type"]


# ── Refusals, across the process boundary ───────────────────────────────────


@pytest.mark.rule("P-8")
def test_a_self_issued_token_without_a_grant_is_refused(holder, verifier):
    """Proving control of your own DID says who you are, not what you may see."""
    token = verifier.sts_token(audience=holder.did)["access_token"]
    assert _ask(holder, token).status_code == 401


def test_a_grant_addressed_to_a_third_party_is_refused(holder, verifier, dcp_exchange):
    """The verifier asks for a token naming somebody else as audience."""
    token = dcp_exchange(audience=verifier.did)
    assert _ask(holder, token).status_code == 401


@pytest.mark.rule("P-8a")
def test_an_unreachable_did_document_is_refused(holder, ephemeral_verifier):
    """A verifier whose DID stops resolving is refused, not trusted on its token.

    The grant is real and unexpired; only the ability to check *who is presenting
    it* is gone. Failing closed here is the difference between "we verified the
    signature" and "we tried to".
    """
    token = run_exchange(holder, ephemeral_verifier)
    assert _ask(holder, token).status_code == 200, "precondition: the exchange works"
    ephemeral_verifier.stop()
    assert not ephemeral_verifier.is_running()
    assert _ask(holder, token).status_code == 401


def test_no_token_is_refused(holder):
    response = httpx.post(
        f"{holder.url}/credentials/{holder.did}/presentations/query",
        json=_query(),
        timeout=10,
    )
    assert response.status_code == 401
