{{- include "ds.externalSecret" (dict "ctx" . "remoteKey" (printf "connector-%s" .Values.participant.name) "keys" (list
    (dict "secretKey" "DB_USER" "property" "db_user")
    (dict "secretKey" "DB_PASSWORD" "property" "db_password")
    (dict "secretKey" "CONNECTOR_CLIENT_SECRET" "property" "client_secret")
    (dict "secretKey" "EDC_CALLBACK_KEY" "property" "edc_callback_key"))) }}
