{{- include "ds.externalSecret" (dict "ctx" . "remoteKey" (printf "connector-%s" .Values.participant.name) "keys" (list
    (dict "secretKey" "DB_USER" "property" "db_user")
    (dict "secretKey" "DB_PASSWORD" "property" "db_password")
    (dict "secretKey" "EDC_API_KEY" "property" "edc_api_key")
    (dict "secretKey" "CONNECTOR_SERVICE_CLIENT_SECRET" "property" "service_client_secret")
    (dict "secretKey" "TRUST_ANCHOR_PUBLIC_JWK" "property" "trust_anchor_public_jwk"))) }}
