{{- include "ds.externalSecret" (dict "ctx" . "remoteKey" "oauth2-proxy" "keys" (list
    (dict "secretKey" "OAUTH2_PROXY_COOKIE_SECRET" "property" "cookie_secret")
    (dict "secretKey" "OAUTH2_PROXY_CLIENT_SECRET" "property" "client_secret"))) }}
