from __future__ import annotations

from functools import lru_cache

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="IDENTITY_REGISTRY_",
        env_file=".env",
        extra="ignore",
        # A field carrying `validation_alias` is otherwise reachable *only* by
        # that alias, so the prefixed form every other setting uses
        # (`IDENTITY_REGISTRY_KEYCLOAK_REALM`) was silently ignored — set it and
        # nothing happened. Both spellings now work. This is additive: no
        # prefixed variant is set anywhere in the repo today, so no existing
        # deployment changes meaning.
        populate_by_name=True,
    )

    database_url: str = (
        "postgresql+asyncpg://postgres:postgres@172.17.0.1:35432/identity_registry"
    )
    debug: bool = False

    encryption_key: str = Field(
        default="dev-encryption-key-change-in-production",
        description="Fernet key for encrypting private keys at rest",
    )

    oidc_issuer_url: str | None = Field(
        default=None,
        description="OIDC issuer URL for JWT verification on admin endpoints",
    )

    oidc_insecure_dev: bool = Field(
        default=True,
        description=(
            "When True AND no issuer is configured, tokens are accepted WITHOUT "
            "signature/audience verification (local dev only). Production MUST set "
            "the issuer URL, which enforces verification regardless of this flag."
        ),
    )

    # Layer B: a foreign IdP's group names → ds role bundles, as JSON.
    #
    #   {"celine-manager": "ds-participant-admin"}
    #
    # Empty (the default) means no translation — correct wherever the realm names
    # its groups the ds way. An alias may only name a **bundle**, never a
    # capability: `ds_auth.parse_group_aliases` drops and logs anything else, so
    # deployment config cannot become a permission table.
    oidc_group_aliases: str = ""

    service_client_id: str = Field(
        default="svc-ds-identity-registry",
        description="Keycloak client ID for this service (used as JWT audience)",
    )

    service_client_secret: str = Field(
        default="svc-ds-identity-registry",
        description="Secret for this service's own outbound calls.",
    )

    keycloak_token_url: str | None = Field(
        default=None,
        description=(
            "Token endpoint for this service's outbound calls. Only used to tell "
            "connectors their participant cache is stale; unset means no "
            "notification, which costs a minute of staleness, not correctness."
        ),
    )

    connector_urls: str = Field(
        default="",
        description=(
            "Comma-separated connector base URLs to notify when the participant "
            "registry changes (promote, suspend, revoke). Empty disables it."
        ),
    )

    # A scope name is vocabulary, not configuration.
    #
    # `admin_scope` / `read_scope` / `resolve_scope` used to live here, and they
    # could not work: the guards in `dependencies.py` check string literals
    # (`require_permission("identity-registry.admin")`), so an operator setting
    # `IDENTITY_REGISTRY_READ_SCOPE` renamed nothing. `admin_scope` was the
    # worse case — it was read in exactly one place, so an override moved a
    # visibility check while leaving every guard on the old name, letting the
    # two disagree about what a caller must hold.
    #
    # A permission is declared in `services/keycloak/clients.yaml`, granted
    # there, reached through a bundle in `ds_auth.bundles`, and checked against
    # a literal. A per-deployment override would let the guard and the realm
    # disagree; they read like a knob and were not one, which is worse than a
    # constant because a constant does not invite an operator to set it.

    keycloak_admin_url: str | None = Field(
        default=None,
        validation_alias="KEYCLOAK_ADMIN_URL",
        description="Keycloak admin API base URL",
    )

    # `keycloak_client_id` / `keycloak_client_secret` were here and
    # authenticated nothing. This service reaches Keycloak two ways, and
    # neither used them: realm writes go through `KeycloakAdminClient` with
    # `keycloak_admin_user` / `keycloak_admin_password`, and a promoted
    # participant's connector secret is *generated by Keycloak* in
    # `ensure_service_client`. The secret was nonetheless `required` by the
    # chart and registered with the production guard, so a deployment could be
    # refused startup over a credential that authenticated nothing.

    default_credential_ttl_days: int = 365
    max_credential_ttl_days: int = 730

    trust_anchor_domain: str = Field(
        default="trust-anchor.dataspaces.localhost",
        description="Domain for the trust-anchor DID",
    )

    # Which half of this service this instance is. See `roles.py`.
    #
    # Defaults to `trust-anchor` so a single-instance deployment — which is every
    # deployment today — keeps serving exactly what it served before. A
    # `participant` instance mounts only the holder surface: its own DID
    # documents, its own STS, its own credential service.
    role: str = Field(
        default="trust-anchor",
        description=(
            "trust-anchor | participant. A participant instance serves only the "
            "DIDs it holds keys for and mounts no registry, issuance or "
            "onboarding route."
        ),
    )

    # ── Provisioning bundle ──────────────────────────────────────────────────
    #
    # A third party configures its own deployment from these, so they must be
    # addresses reachable *from outside this cluster* — an in-cluster service DNS
    # name in a bundle produces a connector that cannot resolve its own trust
    # anchor.
    identity_registry_public_url: str | None = Field(
        default=None,
        description=(
            "Externally reachable base URL of this registry, used in provisioning "
            "bundles. Defaults to https://<trust_anchor_domain> when unset."
        ),
    )

    keycloak_issuer_url: str | None = Field(
        default=None,
        validation_alias="KEYCLOAK_ISSUER_URL",
        description=(
            "Realm issuer URL handed to a third party's connector in its bundle."
        ),
    )

    keycloak_realm: str = Field(
        default="dataspaces",
        validation_alias="KEYCLOAK_REALM",
    )

    # Realm admin credentials, used only to provision a third party's connector
    # client at bundle time. Unset disables that step: the bundle is still issued,
    # without Keycloak credentials in it.
    keycloak_admin_user: str | None = Field(
        default=None, validation_alias="KEYCLOAK_ADMIN_USERNAME"
    )
    keycloak_admin_password: str | None = Field(
        default=None, validation_alias="KEYCLOAK_ADMIN_PASSWORD"
    )

    # ── Keycloak posture ─────────────────────────────────────────────────────
    #
    # May this registry **write** to the realm? Two very different deployments
    # exist and only one of them may:
    #
    # * ds owns the realm — it provisions a promoted third party's connector
    #   client and hands over the secret. Convenient, and the only way a
    #   participant gets working credentials without an operator doing it by hand.
    # * ds is a guest in a realm somebody else administers — `helm/values.yaml`
    #   states Keycloak is "not ours to mutate", and there are no admin rights to
    #   have. Creating clients is not merely disabled, it is not ds's to do.
    #
    # Until now the difference was *inferred* from whether admin credentials
    # happened to be set, so a deployment that supplied them for one reason
    # silently acquired the other behaviour. This makes the posture something a
    # deployment states.
    #
    # Default True preserves today's behaviour; the production guard below
    # requires it to be stated deliberately outside dev.
    keycloak_mutate: bool = Field(
        default=True,
        validation_alias="KEYCLOAK_MUTATE",
        description=(
            "Allow writes into the Keycloak realm (provisioning a promoted "
            "participant's connector client). Set false where ds is a guest in a "
            "realm it does not administer."
        ),
    )

    # ── DCP counterparty verification ────────────────────────────────────────
    #
    # A presentation query is authorized by the *verifier's* self-issued token,
    # whose signature is checked against the key in the verifier's DID document.
    # That means resolving a counterparty DID over HTTP, so the scheme has to
    # match the one the deployment publishes on — `https` everywhere but dev,
    # which serves did:web over plain HTTP through Caddy. It is the same choice
    # the EDC states as `edc.iam.did.web.use.https`, and the two must agree.
    did_web_use_https: bool = Field(
        default=True,
        description="Resolve did:web over HTTPS. False only in local dev.",
    )

    did_resolution_timeout_seconds: float = Field(
        default=5.0,
        description="Timeout for fetching a counterparty's DID document.",
    )

    credentials_context_url: str = Field(
        default="https://dataspaces.localhost/ns/credentials/v1",
        description="Credentials JSON-LD context URL",
    )

    dataspace_uri: str = Field(
        default="https://dataspaces.localhost/dataspace",
        description="Dataspace membership URI",
    )

    @property
    def public_base_url(self) -> str:
        """Where this registry is reachable from outside the cluster.

        The one source for URLs that end up **inside issued credentials** and so
        outlive the process — the StatusList a verifier must fetch, above all.
        Six call sites used to build `https://{trust_anchor_domain}/status/1` by
        hand, which is why every credential in dev carries an `https` URL that
        dev does not serve: a revocation check that cannot fetch the list fails
        closed, so revocation has never been verifiable here.
        """
        return self.identity_registry_public_url or f"https://{self.trust_anchor_domain}"

    def status_list_url(self, list_id: int | str = 1) -> str:
        return f"{self.public_base_url}/status/{list_id}"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
