{{- if not .Values.postgresql.enabled }}
{{- if .Values.config.databaseUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provenance.fullname" . }}-db
  labels:
    {{- include "provenance.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.config.databaseUrl | quote }}
{{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provenance.fullname" . }}-db
  labels:
    {{- include "provenance.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "provenance.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
{{- end }}
