{{- include "ds.externalSecret" (dict "ctx" . "remoteKey" "portal" "keys" (list
    (dict "secretKey" "AUTH_SECRET" "property" "auth_secret")
    (dict "secretKey" "AUTH_KEYCLOAK_SECRET" "property" "auth_keycloak_secret")
    (dict "secretKey" "PORTAL_SERVICE_CLIENT_SECRET" "property" "portal_service_client_secret"))) }}
