apiVersion: v2
name: connector
description: EDC control plane management service for the dataspaces platform
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - edc
  - connector
  - dataspaces
  - dssc
maintainers:
  - name: spindoxlabs
dependencies:
  - name: postgresql
    version: ">=13.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
