{{- include "ds.externalSecret" (dict "ctx" . "remoteKey" (printf "provenance-%s" .Values.participant.name) "keys" (list
    (dict "secretKey" "DB_USER" "property" "db_user")
    (dict "secretKey" "DB_PASSWORD" "property" "db_password"))) }}
