{{- if eq (include "ds.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ds.fullname" . }}
  labels:
    {{- include "ds.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | default (include "ds.db.provenance" .) | quote }}
  DB_PASSWORD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}
{{- end }}
