apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-secret
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-secret: {{ .Values.secrets.authSecret | quote }}
  keycloak-client-secret: {{ .Values.secrets.keycloakClientSecret | quote }}
